<?php
require_once 'app_layout.php';
if (!is_staff()) { header('Location: history_transaksi.php'); exit; }
$role = current_role();
$nama = $_SESSION['nama'] ?? 'Pengguna';
app_start('Dashboard Operasional', 'dashboard');
?>
<div class="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p class="muted text-sm" data-id="Dashboard operasional" data-en="Operational dashboard">Dashboard operasional</p><h1 class="mt-1 text-3xl font-black">Halo, <?= e($nama); ?></h1><p class="muted mt-2 text-sm">Login sebagai <strong><?= e($role); ?></strong> · <span id="last-updated">Memuat data...</span></p></div><div id="active-badge" class="rounded-full bg-emerald-100 px-4 py-2 text-sm font-bold text-emerald-700">● Aktif</div></div>
<section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><article class="surface rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="muted">Menunggu</p><p id="menunggu" class="mt-2 text-3xl font-black text-amber-600">0</p></article><article class="surface rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="muted">Dalam Proses</p><p id="proses" class="mt-2 text-3xl font-black text-blue-600">0</p></article><article class="surface rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="muted">Selesai</p><p id="selesai" class="mt-2 text-3xl font-black text-emerald-600">0</p></article><article class="surface rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="muted">Omset Hari Ini</p><p id="omset" class="mt-2 text-2xl font-black text-indigo-600">Rp 0</p></article></section>
<section class="surface mt-6 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div class="flex flex-wrap items-center justify-between gap-3"><div><h2 class="text-lg font-black">Target penyelesaian hari ini</h2><p class="muted mt-1 text-sm">Selesai dan sudah diambil dibanding seluruh pesanan hari ini.</p></div><strong id="persentase" class="text-3xl font-black text-cyan-600">0%</strong></div><div class="mt-5 h-3 overflow-hidden rounded-full bg-slate-200"><div id="progress" class="h-full rounded-full bg-cyan-500 transition-all" style="width:0%"></div></div></section>
<section class="mt-6 grid gap-4 md:grid-cols-3"><?php if (!is_admin()): ?><a href="transaksi_baru.php" class="surface rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><strong class="text-cyan-700">+ Transaksi baru</strong><p class="muted mt-2 text-sm">Catat pesanan pelanggan.</p></a><?php endif; ?><a href="history_transaksi.php" class="surface rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><strong class="text-indigo-700">Lihat history</strong><p class="muted mt-2 text-sm">Lihat transaksi dan statusnya.</p></a><?php if (is_admin()): ?><a href="laporan.php" class="surface rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><strong class="text-emerald-700">Laporan keuangan</strong><p class="muted mt-2 text-sm">Pantau omset dan grafik pemasukan.</p></a><?php endif; ?></section>
<script>const formatRupiah=value=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(value);let dashboardData=null;function updateDashboardLanguage(){const english=window.ravfEnglish===true;document.getElementById('active-badge').textContent=dashboardData?(dashboardData.aktif?(english?'● Active':'● Aktif'):(english?'● No open orders':'● Tidak ada pesanan terbuka')):(english?'● Loading':'● Memuat');document.getElementById('last-updated').textContent=dashboardData?((english?'Updated ':'Diperbarui ')+new Date().toLocaleTimeString(english?'en-US':'id-ID')):(english?'Loading data...':'Memuat data...')}async function refreshStats(){try{const response=await fetch('dashboard_stats.php',{cache:'no-store'});if(!response.ok)throw new Error();dashboardData=await response.json();['menunggu','proses','selesai'].forEach(key=>document.getElementById(key).textContent=dashboardData[key]);document.getElementById('omset').textContent=formatRupiah(dashboardData.omset);document.getElementById('persentase').textContent=dashboardData.persentase+'%';document.getElementById('progress').style.width=dashboardData.persentase+'%';updateDashboardLanguage()}catch(error){dashboardData=null;updateDashboardLanguage()}}document.addEventListener('ravf-language-changed',updateDashboardLanguage);refreshStats();setInterval(refreshStats,15000);</script>
<?php app_end(); ?>
